#******************************************************************************
# Makefile<ttf2font>                                              DB48X project
#******************************************************************************
#
#  File Description:
#
#    Makefile for the ttf2font tool
#
#
#
#
#
#
#
#
#******************************************************************************
#  (C) 2022 Christophe de Dinechin <christophe@dinechin.org>
#  This software is licensed under the terms outlined in LICENSE.txt
#******************************************************************************
#  This file is part of DB48X.
#
#  DB48X is free software: you can redistribute it and/or modify
#  it under the terms outlined in the LICENSE.txt file
#
#  DB48X is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#******************************************************************************

SOURCES=ttf2font.c
PRODUCTS=ttf2font.exe

PKGCONFIGS=freetype2

MIQ=../../recorder/make-it-quick/
include $(MIQ)rules.mk
